### ISSUE TITLE
Economic sector summary

### ISSUE THREAD

**Issue by danielnaab** [18F/federal-carbon-footprint#26]
As a user I would like a summary of an economic sector, so I can understand which government entities contribute the most GHG emissions via spending to the specified economic sector.

## Questions

- [ ] Can we get a description of an economic sector?
- [ ] Can we link to usaspending.gov pages?
- [ ] Are there real differences between NAICs with the same description and different codes or can they be considered the same for display purposes?

## Tasks

- [ ] Create wireframes
- [x] New route for NAICS sector page
- [x] Show sector in NAICS hierarchy
- [x] Show top "X" agency contributors to the sector in a list or table.
- [x] Agencies link to agency pages
