### ISSUE TITLE
Spending agency summary

### ISSUE THREAD

**Issue by danielnaab** [18F/federal-carbon-footprint#27]
As a user, I would like a summary of a top-level spending agency, so I can understand how this agency's treasury spending contributes to GHG emissions.

## Questions

- [ ] Can we get a textual description of a spending agency?
- [ ] Can we link to usaspending.gov pages?

## Tasks

- [ ] Create wireframes
- [ ] Show agency in Treasury's hierarchy (?)
- [ ] Show top "X" sectors in a list or table.
- [ ] Sectors link to sector pages
